apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alerts
  namespace: monitoring
spec:
  groups:
  - name: pod-restart
    rules:
    - alert: ContainerRestarted
      expr: kube_pod_container_status_restarts_total>0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Container {{ $labels.container }} in pod {{ $labels.pod }} restarted"
        description: "Container {{ $labels.container }} in pod {{ $labels.pod }} (namespace: {{ $labels.namespace }}) has restarted {{ $value }} times in the last 5 minutes"
